<?php

/**
 * @file
 * Contains bmi.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bmi_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bmi module.
    case 'help.page.bmi':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bmi_theme() {
  $theme = null  ; 
  $theme['hello-bmi_page'] = [
				'variables' => ['name' => NULL , 'form'  => NULL  ],
				'template' => 'hello-bmi'
		];
  return $theme;
}
