#services:
#    dcissblog.example:
#        class: dciss\blogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]



services:
    oc_platform.antispam:
        class: dciss\blogBundle\Services\MesServicesMails


services:
    oc_platform.beta.html:
        class: dciss\blogBundle\Beta\BetaHTML